name: cardiax
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python>=3.9,<=3.13
  - jax
  - jaxlib=*=*cuda*
  - cuda-nvcc
  - pip
  - pyvista
  - fenics-basix
  - jaxtyping
  - lineax
  - pyyaml
  - pygmsh
  - meshio
  - vtk<9.4